// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCsLs2kDApF0RoK6uYwt8ch36sbpsWFd1A',
    appId: '1:646568336245:web:898161ddbb570bddb2d13c',
    messagingSenderId: '646568336245',
    projectId: 'levelup-26',
    authDomain: 'levelup-26.firebaseapp.com',
    storageBucket: 'levelup-26.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBCM-iM4c-vmpVrK7aQH0uzAGUC-yoHa7s',
    appId: '1:646568336245:android:395f1099a2c1a28bb2d13c',
    messagingSenderId: '646568336245',
    projectId: 'levelup-26',
    storageBucket: 'levelup-26.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHCn8tgXcxkipfVpK_2TKWUywU7Q-KhFw',
    appId: '1:646568336245:ios:17c1f6b684c4d7ddb2d13c',
    messagingSenderId: '646568336245',
    projectId: 'levelup-26',
    storageBucket: 'levelup-26.firebasestorage.app',
    iosClientId: '646568336245-5r66pfbn5i7seet265clvtqivvkb3rj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDHCn8tgXcxkipfVpK_2TKWUywU7Q-KhFw',
    appId: '1:646568336245:ios:17c1f6b684c4d7ddb2d13c',
    messagingSenderId: '646568336245',
    projectId: 'levelup-26',
    storageBucket: 'levelup-26.firebasestorage.app',
    iosClientId: '646568336245-5r66pfbn5i7seet265clvtqivvkb3rj5.apps.googleusercontent.com',
    iosBundleId: 'com.example.frontend',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCsLs2kDApF0RoK6uYwt8ch36sbpsWFd1A',
    appId: '1:646568336245:web:2bf605f6d732c592b2d13c',
    messagingSenderId: '646568336245',
    projectId: 'levelup-26',
    authDomain: 'levelup-26.firebaseapp.com',
    storageBucket: 'levelup-26.firebasestorage.app',
  );

}